name: ci

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true

    - name: Install dependency (Linux)
      run: |
        sudo apt update 
        sudo apt install libgl1-mesa-dev xorg-dev

    - name: Install dependency (Windows)
      run: |
        sudo apt install mingw-w64
        sudo apt install mingw-w64-x86-64-dev

    - name: Linux build
      run: make linux

    - name: Archive Linux executable file
      uses: actions/upload-artifact@v3
      with:
        path: linux-generator

    - name: Windows build (Cross compile)
      run: make windows

    - name: Archive Windows executable file
      uses: actions/upload-artifact@v3
      with:
        path: windows-generator.exe

    - name: Unit test
      run: make test
